### ISSUE TITLE
Generates a python framework is damaged error.

### ISSUE THREAD

**Issue by ajram23** [olilarkin/SwiftPythonTemplate#1]
<img width="262" alt="Screenshot 2024-11-22 at 12 31 03 PM" src="https://github.com/user-attachments/assets/595465ae-93f7-453f-8392-c089be803502">

BTW would this work for notarization and will it find python embedded inside the app? Have you been able to get that working? That's where I am running into trouble. Any help would be greatly appreciated! Thank you!

**Comment by olilarkin** [comment]
what steps did you take with the repo? Did you clone it via git or download a zip? I think the symlinks inside the Python.framework might have got corrupted.

I just built it on one mac, changed code signing and ran it on another mac. I think that the codesigning and notarization should work but i haven't got that far yet

**Comment by ajram23** [comment]
@olilarkin I downloaded the zip. Did you clone? I have been able to get a version working on with Pykit and beeware stuff but its doesn't get embedded when notarizing. Would love to chat if you have sometime, I am stuck at this last step and would appreciate any help

**Comment by olilarkin** [comment]
You need to clone via git

**Comment by ajram23** [comment]
Thanks @olilarkin Clone seems to have removed the error. I noticed you don't have the hardened environment setting on as yet. Are you planning to get it signed? That's where one seems to run into issues.

**Comment by olilarkin** [comment]
I haven’t got that far yet - I hope it should be possible to sign,
notarize, submit to app store etc. from the beeware docs it seems so

**Comment by ajram23** [comment]
Thanks for getting back. Will try it out in the next day or two. If you successfully get far please post on here if possible. Thanks again for putting his template out there!

**Comment by ajram23** [comment]
Quick update: Tried notarizing and I end up with "“Template” is damaged and can’t be opened. You should move it to the Trash."
<img width="264" alt="Screenshot 2024-11-25 at 2 05 52 PM" src="https://github.com/user-attachments/assets/0c83b15c-c996-48b8-976b-12b276243532">

**Comment by ajram23** [comment]
@olilarkin Got it working and notarized, it was the symbolic links and also didnt need the script for sign binary modules. Thanks for all your help!
